#!/usr/bin/env bash
# The script displays the content of the current directory in a list format where only the part of the name after the first dash is displayed

for _ in *
do
    echo "$_" | cut -f 2 -d '-'
done
